#ifndef DIMENSIONS_H_INCLUDED
#define DIMENSIONS_H_INCLUDED



#endif // DIMENSIONS_H_INCLUDED

#define X0 0
#define Y0 0
#define DIALOG_WIDTH 3*(212+188)
#define DIALOG_HEIGHT 3*(227+12+10)+20

#define X_FILENAME 49
#define Y_FILENAME 10
#define FILENAME_WIDTH 172
#define FILENAME_HEIGHT 9

#define X_LIRE 221
#define Y_LIRE 10
#define LIRE_WIDTH 50
#define LIRE_HEIGHT 9

#define X_TEXT2 10
#define Y_TEXT2 34-14
#define TEXT_WIDTH2 190+188
#define TEXT_HEIGHT2 170+26

#define X_SAVE 80+188
#define Y_SAVE 205+13
#define SAVE_WIDTH 36
#define SAVE_HEIGHT 14-3

#define X_CANCEL 155+188
#define Y_CANCEL 205+13
#define CANCEL_WIDTH 36
#define CANCEL_HEIGHT 14-3


#define X_R_NAME 10
#define Y_R_NAME 10
#define R_NAME_WIDTH 50
#define R_NAME_HEIGHT 10

#define X_R_PASS 10
#define Y_R_PASS 40
#define R_PASS_WIDTH 50
#define R_PASS_HEIGHT 10

#define X_VALID 60
#define Y_VALID 25
#define VALID_WIDTH 20
#define VALID_HEIGHT 10

#define X_GO_TO_EDIT 8
#define Y_GO_TO_EDIT 9
#define WIDTH_GO_TO_EDIT 80
#define HEIGHT_GO_TO_EDIT 10
#define X_GO_TO 11
#define Y_GO_TO 22
#define WIDTH_GO_TO 32
#define HEIGHT_GO_TO 10
#define WIDTH_GO_TO_CANCEL 30
#define HEIGHT_GO_TO_CANCEL 10
#define Y_GO_TO_CANCEL 22
#define X_GO_TO_CANCEL 85-WIDTH_GO_TO_CANCEL//95-WIDTH_GO_TO_CANCEL

#define X_REM_DIALOG 5
#define Y_REM_DIALOG 5
#define WIDTH_REM_DIALOG 200
#define HEIGHT_REM_DIALOG 50
/*#define IDC_OLD_NAME_LABEL 4
#define X_OLD_NAME_LABEL 4
#define Y_OLD_NAME_LABEL 10
#define WIDTH_OLD_NAME_LABEL 40
#define HEIGHT_OLD_NAME_LABEL 6
#define HEIGHT_OLD_NAME_TEXT 6
#define WIDTH_OLD_NAME_TEXT WIDTH_REM_DIALOG - 20
#define Y_OLD_NAME_TEXT  Y_OLD_NAME_LABEL+ HEIGHT_OLD_NAME_LABEL+5
#define X_OLD_NAME_TEXT X_OLD_NAME_LABEL+6
#define IDC_OLD_NAME_TEXT 5
#define HEIGHT_OLD_NAME_OK
#define WIDTH_OLD_NAME_OK
#define X_OLD_NAME_OK
#define Y_OLD_NAME_OK
#define IDC_OLD_NAME_OK
#define HEIGHT_NEW_NAME_TEXT
#define WIDTH_NEW_NAME_TEXT
#define Y_NEW_NAME_TEXT
#define X_NEW_NAME_TEXT
#define HEIGHT_NEW_NAME_LABEL
#define WIDTH_NEW_NAME_LABEL
#define Y_NEW_NAME_LABEL
#define X_NEW_NAME_LABEL*/

